complexity:
  TooManyFunctions:
    active: false
config:
  validation: true
empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
style:
  ForbiddenImport:
    active: true
    imports:
      - 'android.app.main.IconButton' # should use our fork
      - 'androidx.compose.material3.Text' # should use our wrapper
      - 'androidx.compose.material3.IconButton' # should use our fork
      - 'java.util.concurrent.Flow' # probably mean Kotlin's flow
      - 'org.jetbrains.annotations.VisibleForTesting' # standardize on Android's version that lets you specify the "proper" visibility
      - 'org.junit.Test' # use Junit 5
  ForbiddenMethodCall:
    active: true
    methods:
      # all of these should instead use our log wrapper
      - 'kotlin.io.print'
      - 'kotlin.io.println'
      - 'android.util.Log.v'
      - 'android.util.Log.d'
      - 'android.util.Log.i'
      - 'android.util.Log.w'
      - 'android.util.Log.e'
      - 'android.util.Log.wtf'
      - 'android.util.Log.println'
  MaxLineLength:
    maxLineLength: 140
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
# TODO make ForbiddenComment detect TODO without a colon
