config:
  validation: true
naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
style:
  MaxLineLength:
    maxLineLength: 140
  ForbiddenImport:
    active: true
    imports:
      - 'androidx.compose.material3.Text' # force going through our own wrapper
