disabled_rules:
   - cyclomatic_complexity
   - file_length
   - function_body_length
   - function_parameter_count
   - line_length
   - type_body_length

identifier_name:
  excluded:
    - x
    - y
    - i
  max_length:
    warning: 50

excluded:
   - Pods
