disabled_rules:
  # Standard rules we don't want
  - cyclomatic_complexity
  - file_length
  - for_where
  - function_body_length
  - function_parameter_count
  - line_length
  - type_body_length
  # Opt-in rules we don't want
  - balanced_xctest_lifecycle
  - closure_body_length
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - file_name
  - file_types_order
  - function_default_parameter_at_end
  - legacy_objc_type
  - let_var_whitespace
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - no_magic_numbers
  - one_declaration_per_file
  - prefer_nimble
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - required_deinit
  - return_value_from_void_function
  - sorted_enum_cases
  - strong_iboutlet
  - superfluous_else
  - type_contents_order
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  # Standard rules we need to comply with
  - force_try
  # Opt-in rules we need to comply with
  - force_unwrapping
  - implicitly_unwrapped_optional
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle

opt_in_rules:
  - all

identifier_name:
  excluded:
    - x
    - y
    - i
  max_length:
    warning: 50

excluded:
   - Pods
